/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'astro/jsx-runtime';
import { type SkinnedMesh } from 'three';
import { SpotlightWithTarget } from './SpotlightWithTarget';
import { useEffect } from 'react';

type MeshProps = JSX.IntrinsicElements['group'] & {
	showSpotlight?: boolean;
};

export function Lamp({ showSpotlight, ...props }: MeshProps) {
	const { nodes, materials } = useGLTF(`/portfolio3D/models/lampu_jalan.glb`);

	return (
		<group {...props} dispose={null}>
			{/* Mesh utama */}
			<group position={[0, 0, 0.181]}>
				<mesh
					geometry={(nodes.Object_5 as SkinnedMesh).geometry}
					material={materials.Street_Light_1}
				/>
				<mesh
					geometry={(nodes.Object_6 as SkinnedMesh).geometry}
					material={materials.Light_1}
				/>
			</group>
			{/* <group position={[0, 0, -0.266]}>
				<mesh
					receiveShadow
					geometry={(nodes.Object_8 as SkinnedMesh).geometry}
					material={materials.Street_Light_2}
				/>
				<mesh
					receiveShadow
					geometry={(nodes.Object_9 as SkinnedMesh).geometry}
					material={materials.Light_2}
				/>
			</group> */}

			{showSpotlight && (
				<>
					{/* Lampu-lampu berdasarkan Empty Object */}
					{/* <SpotlightWithTarget
						position={[
							nodes['tempat_1'].position.x,
							nodes['tempat_1'].position.y,
							nodes['tempat_1'].position.z,
						]}
						targetPosition={[
							nodes['tempat_1'].position.x - 0.5,
							nodes['tempat_1'].position.y - 1,
							nodes['tempat_1'].position.z,
						]}
						distance={20}
						angle={0.5}
						penumbra={0.5}
						intensity={100}
						color="#CFEFFF"
					/>

					<SpotlightWithTarget
						position={[
							nodes['tempat_2'].position.x,
							nodes['tempat_2'].position.y,
							nodes['tempat_2'].position.z,
						]}
						targetPosition={[
							nodes['tempat_2'].position.x + 0.5,
							nodes['tempat_2'].position.y - 1,
							nodes['tempat_2'].position.z,
						]}
						distance={20}
						angle={0.5}
						penumbra={0.5}
						intensity={100}
						color="#CFEFFF"
					/> */}

					<SpotlightWithTarget
						position={nodes['tempat_3'].position}
						targetPosition={[
							nodes['tempat_3'].position.x,
							nodes['tempat_3'].position.y - 1,
							nodes['tempat_3'].position.z + 0.1,
						]}
						distance={20}
						angle={0.7}
						penumbra={1}
						intensity={50}
						color="#CFEFFF"
					/>
				</>
			)}
		</group>
	);
}

useGLTF.preload(`/portfolio3D/models/lampu_jalan.glb`);
