/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function NatureForStreet(props) {
	const { nodes, materials } = useGLTF(
		`/portfolio3D/models/nature_for_street.glb`,
	);

	return (
		<group {...props} dispose={null}>
			<mesh geometry={nodes.Clover_1.geometry} material={materials.Leaves} />
			<mesh
				geometry={nodes.Clover_2.geometry}
				material={materials['Leaves.001']}
			/>
			<mesh
				geometry={nodes.Plant_1.geometry}
				material={materials['Leaves.003']}
			/>
			<mesh
				geometry={nodes.Plant_1_Big.geometry}
				material={materials['Leaves.004']}
			/>
			<mesh
				geometry={nodes.Plant_1_Big001.geometry}
				material={materials['Leaves.004']}
			/>
			<mesh
				geometry={nodes.Plant_1001.geometry}
				material={materials['Leaves.003']}
			/>
			<mesh
				geometry={nodes.Plant_1002.geometry}
				material={materials['Leaves.003']}
				position={[30.727, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1001.geometry}
				material={materials.Leaves}
				position={[38.729, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2001.geometry}
				material={materials['Leaves.001']}
				position={[38.729, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1002.geometry}
				material={materials.Leaves}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2002.geometry}
				material={materials['Leaves.001']}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1003.geometry}
				material={materials['Leaves.003']}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big002.geometry}
				material={materials['Leaves.004']}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big003.geometry}
				material={materials['Leaves.004']}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1004.geometry}
				material={materials['Leaves.003']}
				position={[46.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1005.geometry}
				material={materials['Leaves.003']}
				position={[76.799, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1003.geometry}
				material={materials.Leaves}
				position={[84.801, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2003.geometry}
				material={materials['Leaves.001']}
				position={[84.801, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1004.geometry}
				material={materials.Leaves}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2004.geometry}
				material={materials['Leaves.001']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1006.geometry}
				material={materials['Leaves.003']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big004.geometry}
				material={materials['Leaves.004']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big005.geometry}
				material={materials['Leaves.004']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1007.geometry}
				material={materials['Leaves.003']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1008.geometry}
				material={materials['Leaves.003']}
				position={[149.218, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1005.geometry}
				material={materials.Leaves}
				position={[157.221, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2005.geometry}
				material={materials['Leaves.001']}
				position={[157.221, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1006.geometry}
				material={materials.Leaves}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2006.geometry}
				material={materials['Leaves.001']}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1009.geometry}
				material={materials['Leaves.003']}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big006.geometry}
				material={materials['Leaves.004']}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big007.geometry}
				material={materials['Leaves.004']}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1010.geometry}
				material={materials['Leaves.003']}
				position={[164.563, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1011.geometry}
				material={materials['Leaves.003']}
				position={[195.29, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1007.geometry}
				material={materials.Leaves}
				position={[203.292, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2007.geometry}
				material={materials['Leaves.001']}
				position={[203.292, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1008.geometry}
				material={materials.Leaves}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2008.geometry}
				material={materials['Leaves.001']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1012.geometry}
				material={materials['Leaves.003']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big008.geometry}
				material={materials['Leaves.004']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big009.geometry}
				material={materials['Leaves.004']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1013.geometry}
				material={materials['Leaves.003']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1014.geometry}
				material={materials['Leaves.003']}
				position={[245.088, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1009.geometry}
				material={materials.Leaves}
				position={[253.09, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2009.geometry}
				material={materials['Leaves.001']}
				position={[253.09, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1010.geometry}
				material={materials.Leaves}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2010.geometry}
				material={materials['Leaves.001']}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1015.geometry}
				material={materials['Leaves.003']}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big010.geometry}
				material={materials['Leaves.004']}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big011.geometry}
				material={materials['Leaves.004']}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1016.geometry}
				material={materials['Leaves.003']}
				position={[260.432, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1017.geometry}
				material={materials['Leaves.003']}
				position={[291.159, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1011.geometry}
				material={materials.Leaves}
				position={[299.162, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2011.geometry}
				material={materials['Leaves.001']}
				position={[299.162, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_1012.geometry}
				material={materials.Leaves}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Clover_2012.geometry}
				material={materials['Leaves.001']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1018.geometry}
				material={materials['Leaves.003']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big012.geometry}
				material={materials['Leaves.004']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1_Big013.geometry}
				material={materials['Leaves.004']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Plant_1019.geometry}
				material={materials['Leaves.003']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short.geometry}
				material={materials.Grass}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall.geometry}
				material={materials['Grass.001']}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short.geometry}
				material={materials['Grass.002']}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall.geometry}
				material={materials['Grass.003']}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short001.geometry}
				material={materials.Grass}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall001.geometry}
				material={materials['Grass.001']}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short002.geometry}
				material={materials.Grass}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall002.geometry}
				material={materials['Grass.001']}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short001.geometry}
				material={materials['Grass.002']}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall001.geometry}
				material={materials['Grass.003']}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short003.geometry}
				material={materials.Grass}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall003.geometry}
				material={materials['Grass.001']}
				position={[54.872, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short004.geometry}
				material={materials.Grass}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall004.geometry}
				material={materials['Grass.001']}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short002.geometry}
				material={materials['Grass.002']}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall002.geometry}
				material={materials['Grass.003']}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short005.geometry}
				material={materials.Grass}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall005.geometry}
				material={materials['Grass.001']}
				position={[15.2, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short006.geometry}
				material={materials.Grass}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall006.geometry}
				material={materials['Grass.001']}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short003.geometry}
				material={materials['Grass.002']}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall003.geometry}
				material={materials['Grass.003']}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short007.geometry}
				material={materials.Grass}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall007.geometry}
				material={materials['Grass.001']}
				position={[42.223, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short008.geometry}
				material={materials.Grass}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall008.geometry}
				material={materials['Grass.001']}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short004.geometry}
				material={materials['Grass.002']}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall004.geometry}
				material={materials['Grass.003']}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short009.geometry}
				material={materials.Grass}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall009.geometry}
				material={materials['Grass.001']}
				position={[80.414, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short010.geometry}
				material={materials.Grass}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall010.geometry}
				material={materials['Grass.001']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short005.geometry}
				material={materials['Grass.002']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall005.geometry}
				material={materials['Grass.003']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short011.geometry}
				material={materials.Grass}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall011.geometry}
				material={materials['Grass.001']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short012.geometry}
				material={materials.Grass}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall012.geometry}
				material={materials['Grass.001']}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short006.geometry}
				material={materials['Grass.002']}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall006.geometry}
				material={materials['Grass.003']}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short013.geometry}
				material={materials.Grass}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall013.geometry}
				material={materials['Grass.001']}
				position={[173.363, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short014.geometry}
				material={materials.Grass}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall014.geometry}
				material={materials['Grass.001']}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short007.geometry}
				material={materials['Grass.002']}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall007.geometry}
				material={materials['Grass.003']}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short015.geometry}
				material={materials.Grass}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall015.geometry}
				material={materials['Grass.001']}
				position={[133.692, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short016.geometry}
				material={materials.Grass}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall016.geometry}
				material={materials['Grass.001']}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short008.geometry}
				material={materials['Grass.002']}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall008.geometry}
				material={materials['Grass.003']}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short017.geometry}
				material={materials.Grass}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall017.geometry}
				material={materials['Grass.001']}
				position={[160.715, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short018.geometry}
				material={materials.Grass}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall018.geometry}
				material={materials['Grass.001']}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short009.geometry}
				material={materials['Grass.002']}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall009.geometry}
				material={materials['Grass.003']}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short019.geometry}
				material={materials.Grass}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall019.geometry}
				material={materials['Grass.001']}
				position={[198.905, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short020.geometry}
				material={materials.Grass}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall020.geometry}
				material={materials['Grass.001']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short010.geometry}
				material={materials['Grass.002']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall010.geometry}
				material={materials['Grass.003']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short021.geometry}
				material={materials.Grass}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall021.geometry}
				material={materials['Grass.001']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short022.geometry}
				material={materials.Grass}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall022.geometry}
				material={materials['Grass.001']}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short011.geometry}
				material={materials['Grass.002']}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall011.geometry}
				material={materials['Grass.003']}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short023.geometry}
				material={materials.Grass}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall023.geometry}
				material={materials['Grass.001']}
				position={[269.232, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short024.geometry}
				material={materials.Grass}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall024.geometry}
				material={materials['Grass.001']}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short012.geometry}
				material={materials['Grass.002']}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall012.geometry}
				material={materials['Grass.003']}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short025.geometry}
				material={materials.Grass}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall025.geometry}
				material={materials['Grass.001']}
				position={[229.561, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short026.geometry}
				material={materials.Grass}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall026.geometry}
				material={materials['Grass.001']}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short013.geometry}
				material={materials['Grass.002']}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall013.geometry}
				material={materials['Grass.003']}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short027.geometry}
				material={materials.Grass}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall027.geometry}
				material={materials['Grass.001']}
				position={[256.584, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short028.geometry}
				material={materials.Grass}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall028.geometry}
				material={materials['Grass.001']}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short014.geometry}
				material={materials['Grass.002']}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall014.geometry}
				material={materials['Grass.003']}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short029.geometry}
				material={materials.Grass}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall029.geometry}
				material={materials['Grass.001']}
				position={[294.775, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short030.geometry}
				material={materials.Grass}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall030.geometry}
				material={materials['Grass.001']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short015.geometry}
				material={materials['Grass.002']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall015.geometry}
				material={materials['Grass.003']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short031.geometry}
				material={materials.Grass}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall031.geometry}
				material={materials['Grass.001']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Short032.geometry}
				material={materials.Grass}
				position={[-14.853, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Common_Tall032.geometry}
				material={materials['Grass.001']}
				position={[-14.853, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Short016.geometry}
				material={materials['Grass.002']}
				position={[-14.853, 0, 0]}
			/>
			<mesh
				geometry={nodes.Grass_Wispy_Tall016.geometry}
				material={materials['Grass.003']}
				position={[-14.853, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1.geometry}
				material={materials.Rocks}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1.geometry}
				material={materials['PathRocks.001']}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide.geometry}
				material={materials['PathRocks.002']}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3.geometry}
				material={materials['Rocks.001']}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide001.geometry}
				material={materials['PathRocks.002']}
				position={[20.22, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1001.geometry}
				material={materials['PathRocks.001']}
				position={[30.727, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1001.geometry}
				material={materials.Rocks}
				position={[38.729, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1002.geometry}
				material={materials.Rocks}
				position={[70.947, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1002.geometry}
				material={materials['PathRocks.001']}
				position={[70.947, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide002.geometry}
				material={materials['PathRocks.002']}
				position={[70.947, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3001.geometry}
				material={materials['Rocks.001']}
				position={[70.947, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide003.geometry}
				material={materials['PathRocks.002']}
				position={[91.167, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1003.geometry}
				material={materials['PathRocks.001']}
				position={[101.674, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1003.geometry}
				material={materials.Rocks}
				position={[109.676, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1004.geometry}
				material={materials.Rocks}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1004.geometry}
				material={materials['PathRocks.001']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide004.geometry}
				material={materials['PathRocks.002']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3002.geometry}
				material={materials['Rocks.001']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide005.geometry}
				material={materials['PathRocks.002']}
				position={[0.019, 0.247, -9.155]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1005.geometry}
				material={materials['PathRocks.001']}
				position={[149.218, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1005.geometry}
				material={materials.Rocks}
				position={[157.221, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1006.geometry}
				material={materials.Rocks}
				position={[189.439, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1006.geometry}
				material={materials['PathRocks.001']}
				position={[189.439, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide006.geometry}
				material={materials['PathRocks.002']}
				position={[189.439, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3003.geometry}
				material={materials['Rocks.001']}
				position={[189.439, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide007.geometry}
				material={materials['PathRocks.002']}
				position={[209.659, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1007.geometry}
				material={materials['PathRocks.001']}
				position={[220.166, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1007.geometry}
				material={materials.Rocks}
				position={[228.168, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1008.geometry}
				material={materials.Rocks}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1008.geometry}
				material={materials['PathRocks.001']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide008.geometry}
				material={materials['PathRocks.002']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3004.geometry}
				material={materials['Rocks.001']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide009.geometry}
				material={materials['PathRocks.002']}
				position={[234.581, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1009.geometry}
				material={materials['PathRocks.001']}
				position={[245.088, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1009.geometry}
				material={materials.Rocks}
				position={[253.09, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1010.geometry}
				material={materials.Rocks}
				position={[285.308, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1010.geometry}
				material={materials['PathRocks.001']}
				position={[285.308, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide010.geometry}
				material={materials['PathRocks.002']}
				position={[285.308, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3005.geometry}
				material={materials['Rocks.001']}
				position={[285.308, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide011.geometry}
				material={materials['PathRocks.002']}
				position={[305.528, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1011.geometry}
				material={materials['PathRocks.001']}
				position={[316.035, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1011.geometry}
				material={materials.Rocks}
				position={[324.037, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_1012.geometry}
				material={materials.Rocks}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Small_1012.geometry}
				material={materials['PathRocks.001']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.RockPath_Round_Wide012.geometry}
				material={materials['PathRocks.002']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Rock_Medium_3006.geometry}
				material={materials['Rocks.001']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common.geometry}
				material={materials.Leaves_TwistedTree}
			/>
			<mesh
				geometry={nodes.Fern_1.geometry}
				material={materials['Leaves.002']}
			/>
			<mesh
				geometry={nodes.Fern_1001.geometry}
				material={materials['Leaves.002']}
			/>
			<mesh
				geometry={nodes.Bush_Common001.geometry}
				material={materials.Leaves_TwistedTree}
			/>
			<group position={[14.143, 0, 0]}>
				<mesh
					geometry={nodes.tree003.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree003_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1002.geometry}
				material={materials['Leaves.002']}
				position={[23.852, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1003.geometry}
				material={materials['Leaves.002']}
				position={[18.93, 0, 0]}
			/>
			<group position={[38.729, 0, 0]}>
				<mesh
					geometry={nodes.tree004.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree004_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1004.geometry}
				material={materials['Leaves.002']}
				position={[38.729, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common002.geometry}
				material={materials.Leaves_TwistedTree}
				position={[36.682, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common003.geometry}
				material={materials.Leaves_TwistedTree}
				position={[65.711, 0, 0]}
			/>
			<group position={[65.711, 0, 0]}>
				<mesh
					geometry={nodes.tree007.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree007_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1005.geometry}
				material={materials['Leaves.002']}
				position={[65.711, 0, 0]}
			/>
			<group position={[65.711, 0, 0]}>
				<mesh
					geometry={nodes.tree010.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree010_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1006.geometry}
				material={materials['Leaves.002']}
				position={[65.711, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common004.geometry}
				material={materials.Leaves_TwistedTree}
				position={[65.711, 0, 0]}
			/>
			<group position={[79.854, 0, 0]}>
				<mesh
					geometry={nodes.tree012.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree012_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1007.geometry}
				material={materials['Leaves.002']}
				position={[89.562, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1008.geometry}
				material={materials['Leaves.002']}
				position={[84.641, 0, 0]}
			/>
			<group position={[104.44, 0, 0]}>
				<mesh
					geometry={nodes.tree013.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree013_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1009.geometry}
				material={materials['Leaves.002']}
				position={[104.44, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common005.geometry}
				material={materials.Leaves_TwistedTree}
				position={[102.392, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common006.geometry}
				material={materials.Leaves_TwistedTree}
				position={[118.492, 0, 0]}
			/>
			<group position={[118.492, 0, 0]}>
				<mesh
					geometry={nodes.tree016.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree016_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1010.geometry}
				material={materials['Leaves.002']}
				position={[118.492, 0, 0]}
			/>
			<group position={[118.492, 0, 0]}>
				<mesh
					geometry={nodes.tree017.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree017_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1011.geometry}
				material={materials['Leaves.002']}
				position={[118.492, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common007.geometry}
				material={materials.Leaves_TwistedTree}
				position={[118.492, 0, 0]}
			/>
			<group position={[132.635, 0, 0]}>
				<mesh
					geometry={nodes.tree019.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree019_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1012.geometry}
				material={materials['Leaves.002']}
				position={[142.343, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1013.geometry}
				material={materials['Leaves.002']}
				position={[137.422, 0, 0]}
			/>
			<group position={[157.221, 0, 0]}>
				<mesh
					geometry={nodes.tree020.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree020_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1014.geometry}
				material={materials['Leaves.002']}
				position={[157.221, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common008.geometry}
				material={materials.Leaves_TwistedTree}
				position={[155.173, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common009.geometry}
				material={materials.Leaves_TwistedTree}
				position={[184.202, 0, 0]}
			/>
			<group position={[184.202, 0, 0]}>
				<mesh
					geometry={nodes.tree027.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree027_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1015.geometry}
				material={materials['Leaves.002']}
				position={[184.202, 0, 0]}
			/>
			<group position={[184.202, 0, 0]}>
				<mesh
					geometry={nodes.tree029.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree029_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1016.geometry}
				material={materials['Leaves.002']}
				position={[184.202, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common010.geometry}
				material={materials.Leaves_TwistedTree}
				position={[184.202, 0, 0]}
			/>
			<group position={[198.346, 0, 0]}>
				<mesh
					geometry={nodes.tree031.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree031_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1017.geometry}
				material={materials['Leaves.002']}
				position={[208.054, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1018.geometry}
				material={materials['Leaves.002']}
				position={[203.133, 0, 0]}
			/>
			<group position={[222.931, 0, 0]}>
				<mesh
					geometry={nodes.tree032.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree032_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1019.geometry}
				material={materials['Leaves.002']}
				position={[222.931, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common011.geometry}
				material={materials.Leaves_TwistedTree}
				position={[220.884, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common012.geometry}
				material={materials.Leaves_TwistedTree}
				position={[214.361, 0, 0]}
			/>
			<group position={[214.361, 0, 0]}>
				<mesh
					geometry={nodes.tree035.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree035_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1020.geometry}
				material={materials['Leaves.002']}
				position={[214.361, 0, 0]}
			/>
			<group position={[214.361, 0, 0]}>
				<mesh
					geometry={nodes.tree036.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree036_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1021.geometry}
				material={materials['Leaves.002']}
				position={[214.361, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common013.geometry}
				material={materials.Leaves_TwistedTree}
				position={[214.361, 0, 0]}
			/>
			<group position={[228.504, 0, 0]}>
				<mesh
					geometry={nodes.tree038.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree038_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1022.geometry}
				material={materials['Leaves.002']}
				position={[238.212, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1023.geometry}
				material={materials['Leaves.002']}
				position={[233.291, 0, 0]}
			/>
			<group position={[253.09, 0, 0]}>
				<mesh
					geometry={nodes.tree039.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree039_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1024.geometry}
				material={materials['Leaves.002']}
				position={[253.09, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common014.geometry}
				material={materials.Leaves_TwistedTree}
				position={[251.042, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common015.geometry}
				material={materials.Leaves_TwistedTree}
				position={[280.072, 0, 0]}
			/>
			<group position={[280.072, 0, 0]}>
				<mesh
					geometry={nodes.tree042.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree042_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1025.geometry}
				material={materials['Leaves.002']}
				position={[280.072, 0, 0]}
			/>
			<group position={[280.072, 0, 0]}>
				<mesh
					geometry={nodes.tree043.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree043_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1026.geometry}
				material={materials['Leaves.002']}
				position={[280.072, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common016.geometry}
				material={materials.Leaves_TwistedTree}
				position={[280.072, 0, 0]}
			/>
			<group position={[294.215, 0, 0]}>
				<mesh
					geometry={nodes.tree045.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree045_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1027.geometry}
				material={materials['Leaves.002']}
				position={[303.923, 0, 0]}
			/>
			<mesh
				geometry={nodes.Fern_1028.geometry}
				material={materials['Leaves.002']}
				position={[299.002, 0, 0]}
			/>
			<group position={[318.801, 0, 0]}>
				<mesh
					geometry={nodes.tree046.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree046_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1029.geometry}
				material={materials['Leaves.002']}
				position={[318.801, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common017.geometry}
				material={materials.Leaves_TwistedTree}
				position={[316.753, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common018.geometry}
				material={materials.Leaves_TwistedTree}
				position={[-30.053, 0, 0]}
			/>
			<group position={[-30.053, 0, 0]}>
				<mesh
					geometry={nodes.tree049.geometry}
					material={materials.Leaves_NormalTree}
				/>
				<mesh
					geometry={nodes.tree049_1.geometry}
					material={materials.Flowers}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1030.geometry}
				material={materials['Leaves.002']}
				position={[-30.053, 0, 0]}
			/>
			<group position={[-30.053, 0, 0]}>
				<mesh
					geometry={nodes.tree050.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree050_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1031.geometry}
				material={materials['Leaves.002']}
				position={[-30.053, 0, 0]}
			/>
			<mesh
				geometry={nodes.Bush_Common019.geometry}
				material={materials.Leaves_TwistedTree}
				position={[-30.053, 0, 0]}
			/>
			<group position={[-15.91, 0, 0]}>
				<mesh
					geometry={nodes.tree052.geometry}
					material={materials['Leaves_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree052_1.geometry}
					material={materials['Flowers.002']}
				/>
			</group>
			<mesh
				geometry={nodes.Fern_1032.geometry}
				material={materials['Leaves.002']}
				position={[-6.202, 0, 0]}
			/>
			<mesh
				geometry={nodes.tree009.geometry}
				material={materials.Leaves_NormalTree}
			/>
			<mesh geometry={nodes.tree009_1.geometry} material={materials.Flowers} />
			<mesh
				geometry={nodes.tree001.geometry}
				material={materials['Leaves_NormalTree.002']}
			/>
			<mesh
				geometry={nodes.tree001_1.geometry}
				material={materials['Flowers.002']}
			/>
		</group>
	);
}

useGLTF.preload(`/portfolio3D/models/nature_for_street.glb`);
