/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function SkillBoardOnStreet(props) {
	const { nodes, materials } = useGLTF(
		`/portfolio3D/models/skills_board_on_street.glb`,
	);
	return (
		<group {...props} dispose={null}>
			<group position={[53.304, 0, 0]}>
				<mesh
					geometry={nodes.astro_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.astro_title.geometry}
					material={materials.title_material}
				/>
				<mesh geometry={nodes.bg_astro.geometry} material={materials.bg_tech} />
				<mesh
					geometry={nodes.bg_image_astro.geometry}
					material={nodes.bg_image_astro.material}
				>
					<mesh
						geometry={nodes.astro_image.geometry}
						material={materials.astro_image_material}
					/>
				</mesh>
			</group>
			<group position={[10.881, 0, 0]}>
				<mesh geometry={nodes.bg_css.geometry} material={materials.bg_tech} />
				<mesh
					geometry={nodes.bg_image_css.geometry}
					material={nodes.bg_image_css.material}
				>
					<mesh
						geometry={nodes.css_image.geometry}
						material={materials.css_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.css_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.css_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[43.603, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_javascript.geometry}
					material={nodes.bg_image_javascript.material}
				>
					<mesh
						geometry={nodes.javascript_image.geometry}
						material={materials.javascript_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_javascript.geometry}
					material={materials.bg_tech}
				/>
				<mesh
					geometry={nodes.javascript_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.javascript_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[43.459, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_nextjs.geometry}
					material={nodes.bg_image_nextjs.material}
				>
					<mesh
						geometry={nodes.nextjs_image.geometry}
						material={materials.nextjs_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_nextjs.geometry}
					material={materials.bg_tech}
				/>
				<mesh
					geometry={nodes.nextjs_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.nextjs_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[62.987, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_reactjs.geometry}
					material={nodes.bg_image_reactjs.material}
				>
					<mesh
						geometry={nodes.Plane006.geometry}
						material={materials.reactjs_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_reactjs.geometry}
					material={materials.bg_tech}
				/>
				<mesh
					geometry={nodes.reactjs_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.reactjs_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[21.855, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_scss.geometry}
					material={nodes.bg_image_scss.material}
				>
					<mesh
						geometry={nodes.Plane002.geometry}
						material={materials.scss_image_material}
					/>
				</mesh>
				<mesh geometry={nodes.bg_scss.geometry} material={materials.bg_tech} />
				<mesh
					geometry={nodes.scss_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.scss_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[34.769, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_tailwindcss.geometry}
					material={nodes.bg_image_tailwindcss.material}
				>
					<mesh
						geometry={nodes.Plane009.geometry}
						material={materials.tailwindcss_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_tailwindcss.geometry}
					material={materials.bg_tech}
				/>
				<mesh
					geometry={nodes.tailwindcss_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.tailwindcss_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[52.777, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_typescript.geometry}
					material={nodes.bg_image_typescript.material}
				>
					<mesh
						geometry={nodes.Plane005.geometry}
						material={materials.typescript_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_typescript.geometry}
					material={materials.bg_tech}
				/>
				<mesh
					geometry={nodes.typescript_description.geometry}
					material={materials.description_material}
				/>
				<mesh
					geometry={nodes.typescript_title.geometry}
					material={materials.title_material}
				/>
			</group>
			<group position={[39.434, 0, 0]}>
				<mesh
					geometry={nodes.bg_image_blender.geometry}
					material={nodes.bg_image_blender.material}
					position={[-16.514, 0, 0]}
				>
					<mesh
						geometry={nodes.blender_image.geometry}
						material={materials.blender_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_figma.geometry}
					material={nodes.bg_image_figma.material}
					position={[-4.732, 0, 0]}
				>
					<mesh
						geometry={nodes.figma_image.geometry}
						material={materials.figma_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_github.geometry}
					material={nodes.bg_image_github.material}
					position={[1.073, 0, 0]}
				>
					<mesh
						geometry={nodes.github_image.geometry}
						material={materials.github_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_jotai.geometry}
					material={nodes.bg_image_jotai.material}
					position={[6.168, 0, 0]}
				>
					<mesh
						geometry={nodes.jotai_image.geometry}
						material={materials.jotai_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_motion.geometry}
					material={nodes.bg_image_motion.material}
					position={[-6.178, 0, 0]}
				>
					<mesh
						geometry={nodes.motion_image.geometry}
						material={materials.motion_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_mysql.geometry}
					material={nodes.bg_image_mysql.material}
					position={[-5.94, 0, 0]}
				>
					<mesh
						geometry={nodes.mysql_image.geometry}
						material={materials.mysql_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_prisma.geometry}
					material={nodes.bg_image_prisma.material}
					position={[18.37, 0, 0]}
				>
					<mesh
						geometry={nodes.prisma_image.geometry}
						material={materials.prisma_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_pwa.geometry}
					material={nodes.bg_image_pwa.material}
					position={[0.156, 0, 0]}
				>
					<mesh
						geometry={nodes.pwa_image.geometry}
						material={materials.pwa_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_restapi.geometry}
					material={nodes.bg_image_restapi.material}
					position={[-16.165, 0, 0]}
				>
					<mesh
						geometry={nodes.restapi_image.geometry}
						material={materials.restapi_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_shadcnui.geometry}
					material={nodes.bg_image_shadcnui.material}
					position={[39.174, 0, 0]}
				>
					<mesh
						geometry={nodes.shadcnui_image.geometry}
						material={materials.shadcnui_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_socketio.geometry}
					material={nodes.bg_image_socketio.material}
					position={[9.648, 0, 0]}
				>
					<mesh
						geometry={nodes.socketio_image.geometry}
						material={materials.socketio_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_tanstack.geometry}
					material={nodes.bg_image_tanstack.material}
					position={[3.187, 0, 0]}
				>
					<mesh
						geometry={nodes.tanstack_image.geometry}
						material={materials.tanstack_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_threejs.geometry}
					material={nodes.bg_image_threejs.material}
					position={[-16.364, 0, 0]}
				>
					<mesh
						geometry={nodes.threejs_image.geometry}
						material={materials.threejs_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_vite.geometry}
					material={nodes.bg_image_vite.material}
					position={[-11.119, 0, 0]}
				>
					<mesh
						geometry={nodes.vite_image.geometry}
						material={materials.vite_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_image_zod.geometry}
					material={nodes.bg_image_zod.material}
					position={[-6.417, 0, 0]}
				>
					<mesh
						geometry={nodes.zod_image.geometry}
						material={materials.zod_image_material}
					/>
				</mesh>
				<mesh
					geometry={nodes.bg_other.geometry}
					material={materials.bg_tech}
					position={[-0.559, 0, 0]}
				>
					<mesh
						geometry={nodes.bg_other_tv.geometry}
						material={materials.bg_tech_tv}
					/>
				</mesh>
				<mesh
					geometry={nodes.other_title.geometry}
					material={materials.title_material}
				/>
				<mesh
					geometry={nodes.other_title001.geometry}
					material={materials.title_material}
				/>
			</group>
			<mesh geometry={nodes.bg_html.geometry} material={materials.bg_tech}>
				<mesh
					geometry={nodes.bg_html_tv.geometry}
					material={materials.bg_tech_tv}
				/>
			</mesh>
			<mesh
				geometry={nodes.bg_image_html.geometry}
				material={nodes.bg_image_html.material}
			>
				<mesh
					geometry={nodes.html_image.geometry}
					material={materials['html_image_material.001']}
				/>
			</mesh>
			<mesh
				geometry={nodes.Text001.geometry}
				material={materials.description_material}
			/>
			<mesh
				geometry={nodes.Text002.geometry}
				material={materials.title_material}
			/>
		</group>
	);
}

useGLTF.preload(`/portfolio3D/models/skills_board_on_street.glb`);
