/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Trees(props) {
	const { nodes, materials } = useGLTF(`/portfolio3D/models/trees.glb`);

	return (
		<group {...props} dispose={null}>
			<group position={[-147.381, 6.203, -8.432]}>
				<mesh
					geometry={nodes.tree023.geometry}
					material={materials.Bark_NormalTree}
				/>
				<mesh
					geometry={nodes.tree023_1.geometry}
					material={materials['Leaves_NormalTree.001']}
				/>
			</group>
			<group position={[-109.262, 5.571, -9.19]}>
				<mesh
					geometry={nodes.tree024.geometry}
					material={materials['Bark_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree024_1.geometry}
					material={materials['Leaves_NormalTree.003']}
				/>
			</group>
			<group position={[-70.176, 5.571, -9.19]} scale={1.1}>
				<mesh
					geometry={nodes.tree025.geometry}
					material={materials['Bark_NormalTree.003']}
				/>
				<mesh
					geometry={nodes.tree025_1.geometry}
					material={materials['Leaves_NormalTree.004']}
				/>
			</group>
			<group position={[-33.483, 7.269, -9.714]} scale={1.2}>
				<mesh
					geometry={nodes.tree026.geometry}
					material={materials['Bark_NormalTree.004']}
				/>
				<mesh
					geometry={nodes.tree026_1.geometry}
					material={materials['Leaves_NormalTree.005']}
				/>
			</group>
			<group position={[-1.699, 0.247, -9.155]} scale={1.2}>
				<mesh
					geometry={nodes.tree053.geometry}
					material={materials['Bark_NormalTree.005']}
				/>
				<mesh
					geometry={nodes.tree053_1.geometry}
					material={materials['Leaves_NormalTree.006']}
				/>
			</group>
			<group position={[39.323, 6.54, -8.432]}>
				<mesh
					geometry={nodes.tree054.geometry}
					material={materials.Bark_NormalTree}
				/>
				<mesh
					geometry={nodes.tree054_1.geometry}
					material={materials['Leaves_NormalTree.001']}
				/>
			</group>
			<group position={[77.443, 5.571, -9.19]}>
				<mesh
					geometry={nodes.tree055.geometry}
					material={materials['Bark_NormalTree.002']}
				/>
				<mesh
					geometry={nodes.tree055_1.geometry}
					material={materials['Leaves_NormalTree.003']}
				/>
			</group>
			<group position={[116.528, 5.571, -9.19]} scale={1.1}>
				<mesh
					geometry={nodes.tree056.geometry}
					material={materials['Bark_NormalTree.003']}
				/>
				<mesh
					geometry={nodes.tree056_1.geometry}
					material={materials['Leaves_NormalTree.004']}
				/>
			</group>
			<group position={[153.222, 7.269, -9.714]} scale={1.2}>
				<mesh
					geometry={nodes.tree057.geometry}
					material={materials['Bark_NormalTree.004']}
				/>
				<mesh
					geometry={nodes.tree057_1.geometry}
					material={materials['Leaves_NormalTree.005']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(`/portfolio3D/models/trees.glb`);
