/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Wall(props) {
	const { nodes, materials } = useGLTF(`/portfolio/models/wall.glb`);

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.wall.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall001.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall002.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall003.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall004.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall005.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall006.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall007.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall008.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall009.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall010.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall011.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall012.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall013.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall014.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall015.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall016.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall017.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall018.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall019.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall020.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall021.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall022.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall023.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall024.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall025.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall026.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall027.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall028.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall029.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall030.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall031.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall032.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall033.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall034.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall035.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall036.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall037.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall038.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall039.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall040.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall041.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall042.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall043.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall044.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall045.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall046.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall047.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall048.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall049.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall050.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall051.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall052.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall053.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall054.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall055.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall056.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall057.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall058.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall059.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall060.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall061.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall062.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall063.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall064.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall065.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall066.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall067.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall068.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall069.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall070.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall071.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
			<mesh
				geometry={nodes.wall072.geometry}
				material={materials.Concrete_fence}
				position={[-177.219, 0, -12.427]}
				scale={0.001}
			/>
		</group>
	);
}

useGLTF.preload(`/portfolio/models/wall.glb`);
